apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: temperature-map-generator
  labels:
    app: temperature-map
    release: "1"
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: temperature-map-generator
            envFrom:
            - secretRef:
                name: tempmap-secrets
            - configMapRef:
                name: tempmap-config
            env:
            - name: POSTGRES_CONNECTION_STRING
              value: "postgres://postgres:mysecretpassword@water.apps.svc.cluster.local:5432/postgres"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONFIG_SCHEDULE
              value: "no"
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources:
              {}
          restartPolicy: OnFailure
