apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: water
  labels:
    app: temperature-map
    release: "1"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: temperature-map
        service: db
        release: "1"
    spec:
      containers:
        - name: temperature-map-water
          envFrom:
          - secretRef:
              name: tempmap-secrets
          - configMapRef:
              name: tempmap-config
          image: "mattb/postgis-water:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command:
              - pg_isready
              - -h
              - localhost
              - -U
              - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - pg_isready
              - -h
              - localhost
              - -U
              - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            {}
