apiVersion: v1
kind: Service
metadata:
  name: water
  labels:
    app: temperature-map
    release: "1"
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: water
  selector:
    service: db
